apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    deployment: kuadrant-qe-pipeline
    app: infra-delete-osd

resources:
  - ../../../tasks/infra/ocm-login-task.yaml
  - ../../../tasks/infra/get-cluster-id-task.yaml
  - ../../../tasks/infra/cluster-secret-cleanup-task.yaml
  - ../../../tasks/infra/delete-osd-task.yaml
  - ../../../tasks/infra/wait-till-osd-is-deleted-task.yaml
  - pipeline.yaml
