apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    deployment: kuadrant-qe-pipeline
    app: infra-rosa

resources:
  - ../../../tasks/infra/rosa-login-task.yaml
  - ../../../tasks/infra/provision-rosa-task.yaml
  - ../../../tasks/infra/wait-till-osd-is-ready-task.yaml
  - ../../../tasks/infra/get-osd-credentials-task.yaml
  - ../../../tasks/infra/wait-for-valid-certificates-task.yaml
  - pipeline.yaml
