apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - uninstall-operators.yaml
  - setup-disconnected.yaml
  - cluster-disconnect.yaml
  - install-operator.yaml
  - disconnected-cleanup.yaml
